---
- name: Pull and Run Nginx Container
  hosts: all
  become: yes

  tasks:
    - name: Pull and run Nginx container
      community.docker.docker_container:
        name: nginx-web
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        pull: true
        ports:
          - "80:80"
