---

global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'tariqbukharimux@gmail.com'
  smtp_auth_username: 'tariqbukharimux@gmail.com'
  smtp_auth_password: 'zhik kxqh ucnn wxuf'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'tariqbukharimux@gmail.com'
        send_resolved: true
